import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/HOC/StoreProvider";
import ThemeProvider from "@/components/HOC/ThemeProvider";
import MySidebar from "@/components/root/MySidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <StoreProvider>
                <body className={inter.className} >
                    <ThemeProvider>
                        <div className="flex">
                            <MySidebar />
                            <div className="flex-1">
                                {children}
                            </div>
                        </div>
                        <MySidebar />
                    </ThemeProvider>
                </body>
            </StoreProvider>
        </html>
    );
}
