import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/HOC/StoreProvider";
import ThemeProvider from "@/components/HOC/ThemeProvider";
import MySidebar from "@/components/root/MySidebar";
import { SocketProvider } from "@/components/HOC/SocketProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <StoreProvider>
                <body className={inter.className}>
                    <ThemeProvider>
                        <SocketProvider>
                            <div className="flex h-screen overflow-x-hidden">
                                <MySidebar />
                                <div className="flex-1 overflow-auto">
                                    {children}
                                </div>
                            </div>
                        </SocketProvider>
                    </ThemeProvider>
                </body>
            </StoreProvider>
        </html>
    );
}
