version: "3.4"

services:
  mainserver:
    container_name: mainserver
    build:
      context: ./mainserver
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./mainserver:/app
      - /app/node_modules
    command: ["nodemon", "app.js"]

  signalingserver:
    container_name: signalingserver
    build:
      context: ./signalingserver
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./signalingserver:/app
      - /app/node_modules
    command: ["nodemon", "app.js"]

  